// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbHTd4LH6NHfbx40VP7qv4sfZ44M65Ok8',
    appId: '1:442237028978:web:20d36ef9d73866713550eb',
    messagingSenderId: '442237028978',
    projectId: 'uas-mobile-2-f8591',
    authDomain: 'uas-mobile-2-f8591.firebaseapp.com',
    storageBucket: 'uas-mobile-2-f8591.firebasestorage.app',
    measurementId: 'G-B7QJ40H0TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFDOTwiCEE_cb5Nm6zew306r4IACxFYo',
    appId: '1:442237028978:android:e8c77177a01f2d8a3550eb',
    messagingSenderId: '442237028978',
    projectId: 'uas-mobile-2-f8591',
    storageBucket: 'uas-mobile-2-f8591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1AXPJyuYpZXCISmWZQaTs_BIMdh3SUNA',
    appId: '1:442237028978:ios:b011d55d84dce2db3550eb',
    messagingSenderId: '442237028978',
    projectId: 'uas-mobile-2-f8591',
    storageBucket: 'uas-mobile-2-f8591.firebasestorage.app',
    iosBundleId: 'com.example.uasmobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1AXPJyuYpZXCISmWZQaTs_BIMdh3SUNA',
    appId: '1:442237028978:ios:b011d55d84dce2db3550eb',
    messagingSenderId: '442237028978',
    projectId: 'uas-mobile-2-f8591',
    storageBucket: 'uas-mobile-2-f8591.firebasestorage.app',
    iosBundleId: 'com.example.uasmobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbHTd4LH6NHfbx40VP7qv4sfZ44M65Ok8',
    appId: '1:442237028978:web:bb6df9f778b944593550eb',
    messagingSenderId: '442237028978',
    projectId: 'uas-mobile-2-f8591',
    authDomain: 'uas-mobile-2-f8591.firebaseapp.com',
    storageBucket: 'uas-mobile-2-f8591.firebasestorage.app',
    measurementId: 'G-X18YNSNZCX',
  );
}
